### ISSUE TITLE
Morning Session Code Review

### ISSUE THREAD

**Issue by stephenkati** [DilsherB/LeaderBoard#5]
**Hello @DilsherB,**
#
**Highlights!**
Good code organization and working app :heavy_check_mark: 
Descriptive README :heavy_check_mark: 
Nice Job getting the leaderboard application setup :heavy_check_mark: 

Cheers and Happy coding!clapclapclap
#
**Suggestions**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

- [ ] https://github.com/DilsherB/LeaderBoard/blob/6410bbf33ebe1c846e5172db51659cc6ef9f4ab1/src/index.js#L23-L24 I think it would be better to use form.reset(). It is a nice and simple way of setting the form fields to null.

**Comment by DilsherB** [comment]
@stephenkati thank you for your review. I have applied this change as it sounds good to make my code compact and elegant.
